pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = 'react-app'
    AWS_ACCOUNT_ID = '529928147146'
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/chimalexoficial/Giphy-App-API.git'
      }
    }

    stage('Build Image') {
      steps {
        sh 'docker build -t $ECR_REPO:latest -f docker/Dockerfile .'
      }
    }

    stage('Login to ECR') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-ecr']]) {
          sh '''
            aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com
          '''
        }
      }
    }

    stage('Push to ECR') {
      steps {
        sh '''
          docker tag $ECR_REPO:latest ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
        '''
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:80 --name react-app \
          ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
        '''
      }
    }
  }
}

